export declare const PROTOCOL_VERSION = 3;
export declare const MAX_VCO_SIZE = 4194304;
export declare const RECON_THRESHOLD = 16;
export declare const IDLE_TIMEOUT_SECONDS = 300;
export declare const MAGIC_BYTES = 1447251715;
export declare const HEADER_HASH_LENGTH = 32;
export declare const FLAG_EPHEMERAL: number;
export declare const FLAG_OBFUSCATED: number;
export declare const FLAG_POW_ACTIVE: number;
export declare const FLAG_ZKP_AUTH: number;
export declare const FLAG_FRAGMENTED: number;
export declare const RESERVED_FLAG_MASK = 15;
export declare const MULTICODEC_ED25519_PUB = 237;
export declare const MULTICODEC_SECP256K1_PUB = 231;
export declare const MULTICODEC_PROTOBUF = 80;
export declare const MULTIHASH_BLAKE3_256 = 30;
export declare const ED25519_PUBLIC_KEY_LENGTH = 32;
export declare const ED25519_SIGNATURE_LENGTH = 64;
export declare const MULTICODEC_VCO_SEQUENCE = 4;
